version: '3.8'

services:

  cashtechbd:
    image: pedrorocs/cash_tech
    container_name: cashtechbd
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: container
      MYSQL_DATABASE: cashtech
      MYSQL_USER: cashtech
      MYSQL_PASSWORD: container
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    networks:
      app_net:
        ipv4_address: 172.20.0.2

  cashtechapp:
    image: murilosbarbosa/cashtech-cli
    container_name: cashtechapp
    command: ["java", "-jar", "/app/cashtech-jar-cli.jar"]
    stdin_open: true
    tty: true
    depends_on:
      - cashtechbd
    environment:
      - DATABASE_HOST=cashtechbd
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=container
      - DATABASE_NAME=cashtech
    networks:
      app_net:
        ipv4_address: 172.20.0.3

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16